# Annotated R code for analysis of differential gene expression in single cell spatial transcriptomics data
# This source code accompanies the following paper that describes the statistical theory behind the analysis:
# G.Margolin, A.Tang, and S.Leikin. Differential expression analysis in single cell and spatial RNASeq without model assumptions.
# Cell Genomics, under review
# bioRxiv preprint: https://www.biorxiv.org/content/10.1101/2025.10.20.683496v1

####################################################
# Requirements for successful code execution:
# R-PACKAGES AND LIBRARIES: dplyr, tidyverse, and Seurat 5.0 or later (may work but not tested with earlier Seurat versions)
# DATA: All data must be assembled into a single Seurat object as described below
# FUNCTIONS: All functions in this file must be loaded by executing the entire code below.
#
#'*IMPORTANT: Instructions for preparing Seurat objects for DGE analysis*
# A Seurat object for DGE analysis based on the functions in this R file must have the following properties:
#       1. Active assay named "RNA". 2. A single layer of counts. 3. Groups of cells to be compared marked by Seurat identities
# Only the counts layer of active "RNA" assay is used for the analysis (data layers are ignored). Therefore, such Seurat objects might be
# assembled in multiple different ways. Below is the simplest approach. 
# Step 1. Create a Seurat object for each group of cells (scRNASeq) or spatial bins (spRNASeq) that will be compared with another group or groups
#         of cells. If possible, do not combine cells from different samples (to usage of such samples as biological replicates).
# Step 2. Make sure that the active assay contains raw, unprocessed counts in a single counts layer (see Seurat documentation for
#         JoinLayers() function)
# Step 3. Create a unique Seurat identity for each cell group: e.g., Idents(object)<-"IdentityName", where object is the name of Seurat object.
# Step 4. Merge all Seurat objects (e.g., object1, object2, object3, and object4) created at steps 1 and 2 into a single Seurat object with a single layer of counts,
#         e.g., FinalObject <- JoinLayers(merge(object1, y=c(object2, object3, object4))). We do not recommend merging objects generated by different types of assays.
#         If necessary, merging of such objects must be preceded by renaming the active assays so that they all have the same name (see step 5)
# Step 5. Make sure that the active assay in the final object is named "RNA". If necessary rename the assay by using Seurat's RenameAssays() function,
#         see Seurat documentation). 
#
####################################################

####################################################
#    LIBRARIES
####################################################
#library(dplyr)
library(Seurat)
#library(tidyverse)
#####################################################

# Internal helpers to keep validation and output handling consistent.
.resolve_features <- function(features, universe) {
  if (is.null(features)) {
    return(list(genes = universe, orphan = character(0)))
  }
  requested <- as.vector(features)
  list(genes = intersect(requested, universe), orphan = setdiff(requested, universe))
}

.warn_orphans <- function(orphan) {
  if (length(orphan) > 0) {
    warning(paste0(toString(orphan), " gene(s) were not found in the object."))
  }
}

.trim_output <- function(output, n_used) {
  if (n_used > 0) {
    output[seq_len(n_used), , drop = FALSE]
  } else {
    output[0, , drop = FALSE]
  }
}

.validate_common_params <- function(fc.thr, min.pct, max.pval, min.count, sum.w2, min.cells) {
  if (!is.numeric(fc.thr) || length(fc.thr) != 1 || is.na(fc.thr) || fc.thr <= 0) {
    stop("fc.thr must be a single positive numeric value")
  }
  if (!is.numeric(min.pct) || length(min.pct) != 1 || is.na(min.pct) || min.pct < 0 || min.pct > 1) {
    stop("min.pct must be a single numeric value in [0,1]")
  }
  if (!is.numeric(max.pval) || length(max.pval) != 1 || is.na(max.pval) || max.pval < 0 || max.pval > 1) {
    stop("max.pval must be a single numeric value in [0,1]")
  }
  if (!is.numeric(min.count) || length(min.count) != 1 || is.na(min.count) || min.count < 0) {
    stop("min.count must be a single non-negative numeric value")
  }
  if (!is.numeric(sum.w2) || length(sum.w2) != 1 || is.na(sum.w2) || sum.w2 <= 0 || sum.w2 > 1) {
    stop("sum.w2 must be a single numeric value in [0,1]")
  }
  if (!is.numeric(min.cells) || length(min.cells) != 1 || is.na(min.cells) || min.cells < 0) {
    stop("min.cells must be a single non-negative numeric value")
  }
}

#####################################################
# DESCRIPTION OF KEY FUNCTIONS
#####################################################
# 1.	DGE.2samples() analyzes DGE between 2 identities or 2 groups of identities in a Seurat object based on weighted-t-test and chi-squared-test.
# 2.	IterWghtTest() same as DGE.2samples but performs only the weighted t-test (called by DGE.2Samples).
# 3.	DGE.Multisample() performs analysis of DGE between 2 groups of samples (at least 3 samples in each group)
#
# Both DGE.2samples() and DGE.Multisample() can be used for scRNASeq and spRNASeq.
# However, different parameters are recommended for different assays (see below).
# In the output from all functions, log2FC is base 2 logarithm of weighted-average.1/weighted-average.2,
# where 1 and 2 mark identities or samples 1 and 2, respectively.
############
#'*DGE.2samples(object,features=NULL,ident.1=NULL,ident.2=NULL,fc.thr=1,min.pct=0,max.pval=1,min.count=30,icc="i",df.correction=FALSE,sum.w2=0.4,min.cells=10)*
# object - Seurat's object for the analysis
# features - list of genes to be analyzed (e.g., features=c("Actb","Actg1",...)), features=NULL causes analysis of all genes (default)
# ident.1 and ident.2 - identities for 2 groups of cells to be analyzed, both must be defined; to combine multiple groups of cells 
#          within ident.1 and/or ident.2 use identity lists, e.g., ident.1 = c("WT1","WT2","WT3")
# fc.thr - fold-change threshold, e.g., fc.thr = 1 results reported for all genes, fc.thr = 2 results reported for genes 
#          that are up- or down-regulated more than 2-fold
# min.pct - minimum fraction of cells expressing the gene in at least one of the 2 groups, e.g., min.pct = 0 results reported for 
#           all genes, min.pct = 0.03 results reported for genes expressed at least by 3% of cells in one of the 2 groups
# max.pval - only genes with p-values less than max.pval are reported
# min.count - similar to min.pct but selects genes for analysis based on the minimum aggregate count, which should exceed min.count
#             in at least in one of the two group; min.count >= 30 is recommended.
# icc - intracluster correlation coefficient (ICC) to be used, allowed values: icc = "i", icc = "A", icc = 0, icc = 1
#       icc = "i" performs weighted t-test with iterative ICC (default)
#       icc = "A" performs weighted t-test with ANOVA ICC (slightly faster but may be less accurate)
#       icc = 0 uses weights based only on total RNA counts per cell (recommended for some spRNASeq assays, see paper)
#       icc = 1 assumes equal weights of all cells and performs common, unweighted t-test
# df.correction - correction for degrees of freedom due to uneven statistical weights; df.correction = TRUE performs a more stringent
#                 weighted t-test when the number of cells is < 30-50 (not recommended)
# sum.w2 - maximum value for the sum of squares of cell weights (default sum.w2=0.4), At sum(w^2)>sum.w2 all cell weights are set to be equal
#          to avoid dominance of just 1 or 2 cells in the weighted average. For more conservative results, use sum.w2=0.1.
# min.cells - minimum number of cells expressing a gene required in one of the two identities for the gene to be analyzed (default min.cells=10) 
#
#'* FUNCTION OUTPUT: dataframe with DGE analysis results*
#'* Output columns:*
# 1. log2FC - log base 2 of fold-change (FC, ident.1/ident2)
# 2. p.value - unadjusted p-value for the fold-chage
# 3. Counts/Cell.1 - Average counts per cell, ident 1
# 4. Counts/Cell.2 - Average counts per cell, ident 2
# Quality control columns in the output:
# 5. N.+_cells.1 - Number of cells expressing the gene, ident 1 
# 6. N.+_cells.2 - Number of cells expressing the gene, ident 2
# 7. Aggregate gene counts, ident 1
# 8. Aggregate gene counts, ident 2
# 9. Sum_w^2.1 - Sum of the squares of stat. weights, ident 1 
# 10. Sum_w^2.2 - Sum of the squares of stat. weights, ident 2 
# 11. Chi2.p.value - unadjusted p.value for aggregate counts in chi-squared test
#
#'* Quality control considerations:* 
# A. Small values of aggregate counts and N.+_cells in both identities precludes reliable statistical inference (not enough data points);
#    min.count parameter eliminates genes with aggregate counts <min.count in both identities, default min.count=30;
#    small aggregate count in just one of two identities does not affect the output accuracy;
#    min.cells parameter eliminates genes with N.+_cells<min.cells in both identities, default min.cells=10.
#    N.+_cells can be small or even zero in just one of the two identities without affecting the output accuracy.
# B. Accurate statistical weight calculation requires sum(w^2)<<1. When sum(w^2)>0.5, just one or two cell define the average. In these
#    cases, unequal statistical weights cannot be used for statistical inference. To avoid such situations, we use sum.w2 parameter.
#    When sum(w^2)>sum.w2 within an identity, all statistical weights within that identity are set to be equal, resulting in conservative
#    estimates for log2FC and p-values (decreasing the likelihood of false positive and increasing the likelihood of false negative findings).
#    The default setting is sum.w2=0.4. Smaller sum.w2 will produce more conservative results. Larger sum.w2 are not advisable.
#    There is no single recipe for optimal sum.w2 setting (use your judgement).
# C. Chi-squared test becomes inaccurate at low aggregate counts and may produce warnings. Borderline values of "Counts" in both samples may indicate reduced accuracy   
# D. Borderline values of N.+_cells and/or Sum_w^2 in both samples may also indicate reduced accuracy.
#    
#############
#'* IterWghtTest(object,features=NULL,ident.1=NULL,ident.2=NULL,fc.thr=1,min.pct=0,max.pval=1,min.count=30,icc="i",df.correction=FALSE,sum.w2=0.4,min.cells=10)*
#   All parameters are the same as in DGE.2samples()
#
# FUNCTION OUTPUT: dataframe with DGE analysis results
# All columns are the same as in DGE.2Samples(), no Chi2.p.value column
#############
#'* DGE.Multisample(object,samples.1=NULL,samples.2=NULL,features=NULL,t.test=FALSE, min.pct=0.03,fc.thr=1,max.pval=1,icc="i",df.correction=FALSE,sum.w2=0.4,min.cells=10,min.count=10)*
# samples.1 and samples.2 - lists of at least 3 identities of biological replicates in each of the 2 groups of samples, e.g.,
#                           samples.1 = c("WT1","WT2","WT3"), samples.2 = c("KO1","KO2","KO3")
#                           renaming multiple technical replicates into the same biological replicate identity is recommended, otherwise 
#                           technical replicates will be treated as biological ones
# t.test - t.test = FALSE performs weighted t-test with iterative ICC when comparing the samples, t.test = TRUE performs common, unweighted 
#                   t-test when comparing the samples
# min.pct, fc.thr, max.pval, df.correction (not recommended), sum.w2, and min.cells are the same parameters as in DGE.2samples()
# icc - same ICC selection as in DGE.2samples(); used for calculating the weighted average values within each sample but not for
#       comparing the two groups of samples
##
# FUNCTION OUTPUT: list of 3 items $DGE is a dataframe containing DGE analysis results, $Sstats is a dataframe containing sample statistics
#                  $parameters is a named list of calculation parameters
# Output columns in $DGE dataframe:
# 1. log2FC - log base 2 of fold-change (FC, samples.1/samples.2)
# 2. p.value - unadjusted p-value for the fold-chage
# 3. Wtd.%UMI.1 - weighted average expression in %UMI, samples.1
# 4. Sd.%UMI.1 - standard deviation of Wtd.%UMI.1 (commonly referred to as standard error of the mean, SEM)
# 5. Av.cell.fr.1 - average fraction of cells expressing the gene, samples.1 (Quality control)
# 6. N.+_cells.1 - number of cells expressing the gene in each sample of samples.1, e.g. N1:N2:N3:N4 means N1 cells in sample 1, N2 in sample 2, N3 in sample 3, and N4 in sample 4
# 7. Counts.1 - Aggregate counts of the gene in each sample of samples.1, same format as N.+_cells.1
# 8. Counts/cell.1 - average counts per cell, samples.1
# 9. Sum_w^2.1 - Sum of the squares of stat. weights of the samples, samples.1 (Quality control)
# 10-16. - same as 3-9 but for samples.2
#
#'* Quality control considerations: *
# A. Please see description of DGE.2Samples() for discussion of min.cells, min.count, and sum.w2 parameters.
#    The same default settings for min.cells and sum.w2 are used in the multi-sample analysis. The default setting of min.count here is 10 rather than 30 since the chi-squared test is not used. However,
#    we recommend caution in interpreting results with low aggregate counts in both groups of samples.
# B. In the context of multi-sample analysis, a gene is excluded from the analysis when the number of samples with enough cells (>=min.cells) expressing the gene drops below 3 in both groups of samples. 
# C. In the context of multi-sample analysis, Sum_w^2 is the sum of squares of statistical weights of samples rather than cells. Otherwise, the same considerations apply. Because the number of samples
#    per group is usually 3-to-5 (minimum 3 required, more than 5 rarely used due to high cost), we do not recommend overwriting the default sum.w2=0.4 setting. Smaller sum.w2 would make sense only for
#    a much larger number of samples while larger sum.w2 reduces accuracy of the results. Sum_w^2 > sum.w2 reported for a sample group means that equal weights were set for all samples in that group.
#    A weighted t-test is identical to a common t-test when the weights are equal within each of the two groups (Sum_w^2>sum.w2 reported for both groups).   
# D. In most cases, strange branches of volcano plots are caused by low expression genes. This can be confirmed by increasing the value of min.cells, which should remove such genes from the analysis.
#    When the number of cells per sample is relatively small to begin with and/or increasing min.cells (excluding insufficiently accurate analysis of low expression genes) is not a good solution for
#    your experiment, an alternative approach is to analyze aggregate rather than weighted average counts by using the setting icc=0 instead of default icc="i" and utilize more conservative common t-test
#    for the samples by setting t.test=TRUE instead of default t.test=FALSE. With these parameter settings, the value of min.cells can be reduced to min.cells=5 (may be even min.cells=3, although this is 
#    a stretch). There is no rigorous mathematical way to evaluate accuracy of such analysis. Trial and error may be the best approach, if you must analyze such data.
# E. Strange volcano plot branches may also indicate a problem in the experiments. For instance, cell-death genes in these branches may indicate presence of dying/dead cells in the selected cell groups.
#    Environment response genes may indicate strong nonlethal effects of cell isolation, causing biased cell selection for the analysis. "Random" genes may indicate RNA contamination. In our experience, 
#    this is always worth following up to ensure high quality of reported results. 
######################################################

######################################################
# ADDITINAL FUNCTIONS
######################################################
# These additional functions included in the source code below and are called by the 3 key functions above:
# alt.wttest() performs weighted t-test using optimized variance estimator (resolves known weights::wtd.t.test() issues).
# alt.wttest2() same as altwttest but with an additional correction for effective degrees of freedom.
# ICC.AN() calculates ANOVA intracluster correlation coefficient (ICC).
# ICC.iter() calculates iterative, ICC providing a more accurate match between estimated and expected variances of the data compared to ANOVA ICC.
# ICCWeight() calculates statistical weights of cells based on ICC values.
# CntAv() performs weighted averaging or aggregation of counts for multisample DGE analysis, depending on parameter setting.
# SampleMatrix() assembles a matrix of weighted average counts and variances for multisample DGE analysis.
# IterVar() calculates iterative ICC for multisample analysis.
# WT.MultiSample() performs weighted t-test analysis of DGE using SampleMatrix() output.


###########################################################################################################
#     Functions for 2-sample scRNASeq analysis
#
###########################################################################################################
#
DGE.2samples <- function(object,features=NULL,ident.1=NULL,ident.2=NULL,
                         fc.thr=1,min.pct=0,max.pval=1,min.count=30,
                         icc="i",df.correction=FALSE,sum.w2=0.4,min.cells=10) {
  .validate_common_params(fc.thr = fc.thr, min.pct = min.pct, max.pval = max.pval,
                          min.count = min.count, sum.w2 = sum.w2, min.cells = min.cells)
  IWT<-IterWghtTtest(object,features,ident.1,ident.2,fc.thr,min.pct,max.pval=max.pval,min.count,icc=icc,df.correction,sum.w2,min.cells)
  Chi2<-Chi2Test(object,features=rownames(IWT),ident.1,ident.2,fc.thr=1,min.pct,max.pval=1,min.count)
  features<-intersect(rownames(Chi2),rownames(IWT))
  output<-IWT[features,]
  output[features,"Chi2.p.value"]<-Chi2[features,2]
  return(output)
}
#Chi2 test
Chi2Test <- function(object,features=NULL,ident.1=NULL,ident.2=NULL,fc.thr=1,min.pct=0,max.pval=1,min.count=30) {
  fr <- .resolve_features(features, rownames(object))
  GL <- fr$genes
  OrphanGenes <- fr$orphan
  .validate_common_params(fc.thr = fc.thr, min.pct = min.pct, max.pval = max.pval,
                          min.count = min.count, sum.w2 = 0.4, min.cells = 0)
  if (is.null(ident.1) || is.null(ident.2)) {stop("Two identities in a Seurat object must be defined using ident.1= and ident.2=")}
  nmax <- length(GL)
  output <- data.frame(log2FC=rep(NA_real_, nmax), p.value=rep(NA_real_, nmax),
                       `Counts/Cell.1`=rep(NA_real_, nmax), `Counts/Cell.2`=rep(NA_real_, nmax),
                       check.names = FALSE)                                                                            # preallocated output dataframe
  rowi <- 0
  if(length(GL)>0){
    object.1 <- subset(object, idents = ident.1)                                                                       # object subsetting
    object.2 <- subset(object, idents = ident.2)
    Ci.1 <- object.1[["RNA"]]$counts                                                                                   # count matrices
    Ci.2 <- object.2[["RNA"]]$counts
    Nc.1 <- ncol(Ci.1)                                                                                                 # number of cells
    Nc.2 <- ncol(Ci.2)
    AC.1 <- Matrix::rowSums(Ci.1)                                                                                      # aggregate counts /gene
    AC.2 <- Matrix::rowSums(Ci.2)
    NCD.1 <- Matrix::rowSums(Ci.1 != 0)                                                                                # positive cell counts /gene
    NCD.2 <- Matrix::rowSums(Ci.2 != 0)
    TC.1 <- sum(AC.1)                                                                                                  # total counts /sample
    TC.2 <- sum(AC.2)
    print("Performing chi^2 test:")
    pb <- txtProgressBar(min = 0, max = length(GL), initial = 0, style = 3)                                            # initialize progress bar
    for (rownum in seq_along(GL)) {                                                                                     # main loop, gene by gene
      gene <- GL[[rownum]]
      if ((AC.1[gene] >= min.count || AC.2[gene] >= min.count) &&                                                      # checking for min.count and min.pct
          ((NCD.1[gene]/Nc.1>min.pct) || (NCD.2[gene]/Nc.2>min.pct))){
        ContTable <- matrix(c(TC.1 - AC.1[gene], TC.2 - AC.2[gene],                                                    # contingency table for chi2 test
                              AC.1[gene], AC.2[gene]), nrow = 2, ncol = 2)
        fc <- as.numeric((AC.1[gene]/TC.1)/(AC.2[gene]/TC.2))                                                           # fold change (FC)
        if(!is.na(fc)){                                                                                                # removing features with undefined FC (=0/0)
          if (fc >= fc.thr || fc <= 1/fc.thr) {                                                                        # checking FC threshold
            chisquare <- as.numeric(chisq.test(ContTable)$p.value)                                                     # chi2 test
            if (chisquare <= max.pval) {                                                                               # checking max.pval threshold
              rowi<-rowi+1
              output[rowi, ] <- c(log(fc,2), chisquare, AC.1[gene]/Nc.1, AC.2[gene]/Nc.2)                            # output assembly
              row.names(output)[rowi]<-gene
            }  
          }
        }
      }
      setTxtProgressBar(pb, rownum)                                                                                    # progress bar update
    }
    close(pb)                                                                                                          # close progress bar                           
  }
  output <- .trim_output(output, rowi)
  .warn_orphans(OrphanGenes)
  return(output)
}
#Weighted t-test with iterative weight calculation
IterWghtTtest <- function(object,features=NULL,ident.1=NULL,ident.2=NULL,fc.thr=1,min.pct=0,max.pval=1,min.count=30,
                          icc="i",df.correction=FALSE,sum.w2=0.4,min.cells=10) {
  fr <- .resolve_features(features, rownames(object))
  GeneList <- fr$genes
  OrphanGenes <- fr$orphan
  .validate_common_params(fc.thr = fc.thr, min.pct = min.pct, max.pval = max.pval,
                          min.count = min.count, sum.w2 = sum.w2, min.cells = min.cells)
  if (is.null(ident.1) || is.null(ident.2)) {stop("Two identities in a Seurat object must be defined using ident.1= and ident.2=")}
  nmax <- length(GeneList)
  output <- data.frame(log2FC=rep(NA_real_, nmax), p.value=rep(NA_real_, nmax),                          # preallocated output dataframe
                       `Counts/Cell.1`=rep(NA_real_, nmax), `Counts/Cell.2`=rep(NA_real_, nmax),
                       `N.+_cells.1`=rep(NA_real_, nmax), `N.+_cells.2`=rep(NA_real_, nmax),
                       `Counts.1`=rep(NA_real_, nmax), `Counts.2`=rep(NA_real_, nmax),
                       `Sum_w^2.1`=rep(NA_real_, nmax), `Sum_w^2.2`=rep(NA_real_, nmax),
                       check.names = FALSE)
  object.1 <- subset(object, idents = ident.1)                                                           # ident.1 object
  Ci.1 <- object.1[["RNA"]]$counts                                                                        # ident.1 count matrix (sparse)
  Ni.1 <- Matrix::colSums(Ci.1)                                                                          # ident.1 Ni vector
  Nc.1 <- ncol(Ci.1)                                                                                     # ident.1 number of cells
  object.2 <- subset(object, idents = ident.2)
  Ci.2 <- object.2[["RNA"]]$counts
  Ni.2 <- Matrix::colSums(Ci.2)
  Nc.2 <- ncol(Ci.2)
  AC.1 <- Matrix::rowSums(Ci.1)
  AC.2 <- Matrix::rowSums(Ci.2)
  NCD.1 <- Matrix::rowSums(Ci.1 != 0)
  NCD.2 <- Matrix::rowSums(Ci.2 != 0)
  CandidateGenes <- GeneList[(AC.1[GeneList] >= min.count | AC.2[GeneList] >= min.count) &
                               (NCD.1[GeneList] >= min.cells | NCD.2[GeneList] >= min.cells) &
                               ((NCD.1[GeneList]/Nc.1 > min.pct) | (NCD.2[GeneList]/Nc.2 > min.pct))]
  if (length(CandidateGenes) > 0L) {
    if (!requireNamespace("MatrixExtra", quietly = TRUE)) {
      stop("Package 'MatrixExtra' is required for CSR row-wise access in this version.")
    }
    Ri.1 <- MatrixExtra::as.csr.matrix(Ci.1)
    Ri.2 <- MatrixExtra::as.csr.matrix(Ci.2)
    gene_idx_1 <- match(CandidateGenes, rownames(Ri.1))
    gene_idx_2 <- match(CandidateGenes, rownames(Ri.2))
  }
  rowi<-0
  print("Performing weighted t-test:")
  pb <- txtProgressBar(min = 0, max = max(1L, length(CandidateGenes)), initial = 0, style = 3)          # initialize progress bar# output row counter
  processed <- 0L
  if (length(CandidateGenes) > 0) {
    for (i in seq_along(CandidateGenes)) {                                                                  # Main test loop with sparse CSR row access
      gene <- CandidateGenes[[i]]
      AC1 <- AC.1[gene]                                                                                     # ident.1 aggregated counts
      AC2 <- AC.2[gene]                                                                                     # ident.2 aggregated counts
      Ncd.1 <- NCD.1[gene]                                                                                  # number of cells expressing the gene
      Ncd.2 <- NCD.2[gene]
      h1 <- as.numeric(Ri.1[gene_idx_1[[i]], , drop = FALSE])
      h2 <- as.numeric(Ri.2[gene_idx_2[[i]], , drop = FALSE])
      Xi1 <- h1/Ni.1                                                                                        # ident.1 normalized counts
      Xi2 <- h2/Ni.2                                                                                        # ident.2 normalized counts
      wi.1 <- ICCWeight(h = h1, n = Ni.1, icc = icc)                                                       # ident.1 weights
      wi.2 <- ICCWeight(h = h2, n = Ni.2, icc = icc)                                                       # ident.2 weights
      wi.1sq <- sum(wi.1^2)                                                                                # sum of w^2
      wi.2sq <- sum(wi.2^2)
      wi.1 <- if(wi.1sq>sum.w2) {rep(1/Nc.1, Nc.1)} else {wi.1}                                            # switching to equal weights when sum(w^2)>sum.w2 (conservative average and variance calculation when 1 cell appears to dominate)
      wi.2 <- if(wi.2sq>sum.w2) {rep(1/Nc.2, Nc.2)} else {wi.2}
      fc <- sum(Xi1*wi.1)/sum(Xi2*wi.2)                                                                    # fold change
      if (!is.na(fc)){                                                                                      # removing 0/0 division
        if ((fc >= fc.thr || fc <= 1/fc.thr)) {                                                            # checking FC threshold
          if(df.correction==TRUE) {wTtest <- as.numeric(alt.wttest2(Xi1,Xi2,wi.1,wi.2))}                  # weighted t-test with effective df
          else {wTtest <- as.numeric(alt.wttest(Xi1,Xi2,wi.1,wi.2))}                                       # weighted t-test without df correction
          if (wTtest <= max.pval) {                                                                         # checking p-value threshold
            rowi<-rowi+1                                                                                    # output row counter
            output[rowi, ] <- c(log(fc,2), wTtest, AC1/Nc.1, AC2/Nc.2, Ncd.1, Ncd.2, AC1, AC2, wi.1sq, wi.2sq) # output
            row.names(output)[rowi]<-gene
          }
        }
      }
      processed <- processed + 1L
      setTxtProgressBar(pb, processed)                                                                      # progress bar update
    }
  }
  close(pb)                                                                                              # close progress bar
  output <- .trim_output(output, rowi)
  .warn_orphans(OrphanGenes)
  return(output)
}
alt.wttest <- function(x1, x2, w1, w2) {
  # alternative weighted t-test based on Margolin-Leikin variance estimator
  stopifnot(length(x1)==length(w1) && length(x2)==length(w2))
  w1 = w1/sum(w1)
  m1 = sum(x1*w1)
  vm1 = sum(w1^2*(x1-m1)^2) / (1-sum(w1^2)) # unbiased when w ~ 1/s^2 (and sum(w)=1)
  w2 = w2/sum(w2)
  m2 = sum(x2*w2)
  vm2 = sum(w2^2*(x2-m2)^2) / (1-sum(w2^2)) # unbiased when w ~ 1/s^2 (and sum(w)=1)
  s12 = sqrt(vm1 + vm2)
  t = (m1 - m2) / s12
  df = s12^4 / (vm1^2/(length(x1)-1) + vm2^2/(length(x2)-1)) 
  p = 2*pt(-abs(t), df=df)
  return(p)
}
alt.wttest2 <- function(x1, x2, w1, w2) {
  # alternative weighted t-test based on Margolin-Leikin variance estimator and effective degrees of freedom
  stopifnot(length(x1)==length(w1) && length(x2)==length(w2))
  w1 = w1/sum(w1)
  n1 = 1/sum(w1^2)
  m1 = sum(x1*w1)
  vm1 = sum(w1^2*(x1-m1)^2) / (1-1/n1) # unbiased when w ~ 1/s^2 (and sum(w)=1)
  w2 = w2/sum(w2)
  n2 = 1/sum(w2^2)
  m2 = sum(x2*w2)
  vm2 = sum(w2^2*(x2-m2)^2) / (1-1/n2) # unbiased when w ~ 1/s^2 (and sum(w)=1)
  s12 = sqrt(vm1 + vm2)
  t = (m1 - m2) / s12
  df = s12^4 / (vm1^2/(n1-1) + vm2^2/(n2-1)) 
  p = 2*pt(-abs(t), df=df)
  return(p)
}
#Calculation of weights based on ICC
ICC.AN<-function(h,n){
  N=sum(n)                                                    #ANOVA ICC calculation
  k=length(n)
  n0=(1/(k-1))*(N-sum(n^2/N))
  MSw=(1/(N-k))*(sum(h)-sum(h^2/n))
  MSb=(1/(k-1))*(sum(h^2/n)-(1/N)*(sum(h))^2)
  if ((MSb+(n0-1)*MSw)==0) {ICC=0}                            #setting ICC=0 when ANOVA denominator = 0
  else ICC=(MSb-MSw)/(MSb+(n0-1)*MSw)
  if(ICC < 0) ICC=0                                           #resetting negative ICC to 0
  if(ICC > 1) ICC=1                                           #resetting ICC>1 to ICC=1
  return(ICC)
}
ICC.iter<-function(h,n){                                      #Iterative ICC calculation
  x=h/n
  w0<-n/sum(n)                                              # initial weights 
  x0<-sum(x*w0)                                             # initial weighted average count
  VarT0<-x0*(1-x0)/sum(n)                                   # initial variance @ icc=0
  VarE0<-sum(w0^2*(x-x0)^2)/(1-sum(w0^2))                   # initial measured variance with w0 weights
  if (VarE0<=VarT0){icc=0}    
  else{
    f <- function(icc,h=h,n=n) {
      x = h/n                                                   #normalized counts
      wprop = n/(1 + icc*(n-1))                                 #proportional weights
      w <- wprop/sum(wprop)                                     #normalized weights
      x1 = sum(x*w)                                             #weighted average
      VarT<-x1*(1-x1)/(sum(wprop))                              #VarT 
      VarE<-sum(w^2*(x-x1)^2)/(1-sum(w^2))                      #VarE
      VarE-VarT                                                 #VarE-VarT
    }
    ur = uniroot(f, 0:1, n=n, h=h, check.conv=T, extendInt="downX", tol = 1e-4/max(n))
    icc = ur$root
    if(icc > 1) icc=1                                           #resetting ICC>1 to ICC=1
  }
  return(icc)
}
ICCWeight <- function(h,n,icc="i") {                     #Calculation of weights based on ICC
  Nc<-length(n)
  if(length(h)!=Nc) {stop("Unequal lengths of Ni and Nzi vectors")} 
  if(Nc<3) {stop("At least 3 cells are required in each ident")}
  if (sum(h!=0)<3){w<-rep(1/Nc,Nc)} #exit and return equal weights if the number cells/samples with nonzero counts is less than 3
  else {
    if(icc=="i"){icc=ICC.iter(h,n)} else {
      if(icc=="A"){icc=ICC.AN(h,n)} else {
        if (icc==0) {icc=0} else {
          if (icc==1) {icc=1} else {
            stop("Invalid icc, must be icc = 'i', 'A', 0, or 1")
          }
        }  
      }
    } 
    wprop = n/(1 + icc*(n-1))                                 #proportional weights
    w <- wprop/sum(wprop)
  }
  return(w)
}
###########################################################################################################
#     Functions for multi-sample scRNASeq analysis
#
#     Recommended usage for scRNASeq and low resolution spRNASeq (Visium): results<-DGE.MultiSample(object, samples.1=c(...), samples.2=c(...))
#     Recommended usage for high resolution spRNASeq (VisiumHD): results<-DGE.MultiSample(object, samples.1=c(...), samples.2=c(...), icc=0)
#     Recommended usage for all assays: reassemble Seurat object(s) from raw counts after QC by using CreateSeuratObject()
#
#     All functions use only the "counts" slot and are independent of Seurat data transformations
#
###########################################################################################################
# Count averaging and variance calculation
# Usage: modified.object<-CntAv(object)
# Returns the original object with weighted average counts, their variances, and other sample stats added to object@misc 
CntAv<-function(object,features=NULL,icc="i"){
  fr <- .resolve_features(features, rownames(object))
  GeneList <- fr$genes                                                                   # check for genes to be analyzed
  OrphanGenes <- fr$orphan
  object@misc$AV.data<-list()                                                            # creating AV.data list in misc slot of the Seurat object 
  Samples<-levels(object@active.ident)                                                   # retrieving sample identities from the object
  Ns<-length(Samples)                                                                    # number of samples in the object
  Sstats<-matrix(nrow=3,ncol=Ns)
  colnames(Sstats)<-Samples
  rownames(Sstats)<-c("N.cells","N.counts","Counts/cell")
  Ng<-length(GeneList)
  if (Ng > 0L && !requireNamespace("MatrixExtra", quietly = TRUE)) {
    stop("Package 'MatrixExtra' is required for CSR row-wise access in this version.")
  }
  print("Averaging counts and calculating variance for each sample:")
  pb <- txtProgressBar(min = 0, max = Ns * Ng, initial = 0, style = 3)                   # initialize progress bar# number of genes    
  for (j in seq_len(Ns)){                                                                 # main loop for calculating weighted average and variance sample by sample
    sample=Samples[j]
    OBJ<-subset(object, idents=sample)                                                   # sample subsetting
    Ci<-OBJ[["RNA"]]$counts                                                               # count matrix
    Ni<-Matrix::colSums(Ci)                                                               # total counts vector (Ni)
    AC<-Matrix::rowSums(Ci)
    Nc<-ncol(Ci)                                                                         # number of cells
    Sstats["N.cells",j]<-Nc
    Sstats["N.counts",j]<-sum(Ni)
    Sstats["Counts/cell",j]<-Sstats["N.counts",j]/Sstats["N.cells",j]
    AV<-numeric(Ng)                                                                      # vector initialization
    VAR<-numeric(Ng)
    PCT<-numeric(Ng)
    CNT<-numeric(Ng)
    NCD<-numeric(Ng)
    AGC<-numeric(Ng)
    Ri <- if (Ng > 0L) MatrixExtra::as.csr.matrix(Ci) else NULL                          # one-time CSR conversion for fast row access
    gene_idx <- if (Ng > 0L) match(GeneList, rownames(Ri)) else integer(0)
    for (i in seq_len(Ng)){                                                               # gene by gene calculation subloop 
      h<-as.numeric(Ri[gene_idx[[i]], , drop = FALSE])                                   # vector of counts for gene i
      Nd<-sum(h!=0)                                                                      # number of cells expressing the gene
      w<-ICCWeight(h=h,n=Ni,icc=icc)                                                     # statistical weights
      x<-as.vector(100*h/Ni)                                                             # normalized genes counts
      AV[i]<-sum(x*w)                                                                    # weighted average gene count (% UMI)
      VAR[i]<-if(AV[i]!=0){sum(w^2*(x-AV[i])^2)/(1-sum(w^2))} else{1/(sum(Ni)^2)}        # variance of the weighted average or 1/sum(Ni)^2 when all x=0
      PCT[i]<-Nd/Nc                                                                      # fraction of cells expressing the gene
      CNT[i]<-mean(h)                                                                    # average counts per cell
      NCD[i]<-Nd
      AGC[i]<-as.numeric(AC[GeneList[i]])
      setTxtProgressBar(pb, (j - 1) * Ng + i)                                            # progress bar update
    }
    AVdat<-cbind(AV,VAR,PCT,CNT,NCD,AGC)                                                 # output matrix assembly
    rownames(AVdat)<-GeneList
    object@misc$AV.data[[sample]]<-as.data.frame(AVdat)                                  # writing output matrix into AV.data list within misc slot
  }
  close(pb)                                                                              # close progress bar
  object@misc$AV.data[["Sstats"]]<-as.data.frame(Sstats)
  .warn_orphans(OrphanGenes)
  return(object)
}
#
# Sample matrix generation
# Usage: sample.matrix<-SampleMatrix(object, samples.1=c(...),samples.2=c(...)); the object must be generated by CntAv()
# generates matrix of weighted average counts, variances, and expression fractions for subsequent analysis
SampleMatrix<-function(object,samples.1=NULL,samples.2=NULL){
  if(is.null(samples.1) || is.null(samples.2)) {stop("Define sample name vectors using samples.1= and samples.2=")}
  N.1=length(samples.1)                                                                  # number of samples in group 1
  N.2=length(samples.2)                                                                  # number of samples in group 2
  if(N.1<3 || N.2<3) {stop("At least 3 samples per group are required")}                 # checking for at least 3 samples per group
  Ng=nrow(object@misc$AV.data[[samples.1[1]]])                                           # number of genes
  if (is.null(Ng)) {stop("Cannot find average data matrix in the object. Please run CntAv()")}
  AV.1<-matrix(0,nrow=Ng,ncol=N.1)                                                       # initialization of sample matrices
  colnames(AV.1)=samples.1
  rownames(AV.1)=rownames(object@misc$AV.data[[samples.1[1]]])
  VAR.1<-AV.1
  PCT.1<-AV.1
  CNT.1<-AV.1
  NCD.1<-AV.1
  AGC.1<-AV.1
  AV.2<-matrix(0,nrow=Ng,ncol=N.2)
  colnames(AV.2)=samples.2
  rownames(AV.2)=rownames(AV.1)
  VAR.2<-AV.2
  PCT.2<-AV.2
  CNT.2<-AV.2
  NCD.2<-AV.2
  AGC.2<-AV.2
  print("Generating sample matrix:")
  pb <- txtProgressBar(min = 0, max = N.1 + N.2, initial = 0, style = 3)                 # initialize progress bar
  for (i in seq_len(N.1)) {                                                               # reading object@misc$AV.data created by CntAv()
    AV.1[,i]<-object@misc$AV.data[[samples.1[i]]]$AV                                     # into sample matrices for groups 1 and 2
    VAR.1[,i]<-object@misc$AV.data[[samples.1[i]]]$VAR
    PCT.1[,i]<-object@misc$AV.data[[samples.1[i]]]$PCT
    CNT.1[,i]<-object@misc$AV.data[[samples.1[i]]]$CNT
    NCD.1[,i]<-object@misc$AV.data[[samples.1[i]]]$NCD
    AGC.1[,i]<-object@misc$AV.data[[samples.1[i]]]$AGC
    setTxtProgressBar(pb, i)                                                             # progress bar update
  }
  for (i in seq_len(N.2)) {
    AV.2[,i]<-object@misc$AV.data[[samples.2[i]]]$AV
    VAR.2[,i]<-object@misc$AV.data[[samples.2[i]]]$VAR
    PCT.2[,i]<-object@misc$AV.data[[samples.2[i]]]$PCT
    CNT.2[,i]<-object@misc$AV.data[[samples.2[i]]]$CNT
    NCD.2[,i]<-object@misc$AV.data[[samples.2[i]]]$NCD
    AGC.2[,i]<-object@misc$AV.data[[samples.2[i]]]$AGC
    setTxtProgressBar(pb, i + N.1)                                                       # progress bar update
  }
  close(pb)                                                                              # close progress bar
  Sstats<-object@misc$AV.data[["Sstats"]]
  samples.matrix<-list(AV.1,VAR.1,AV.2,VAR.2,PCT.1,PCT.2,                                # assembling a single list of sample matrices for
                       CNT.1,CNT.2,NCD.1,NCD.2,AGC.1,AGC.2,Sstats=Sstats)                # for subsequent analysis
  return(samples.matrix)                                        
}
#
# Weight calculation for average,variance vectors
# used by WT.MultiSample() function below
IterVar<-function(Av,Va){                                                                
  Nv<-length(Va)                                                                         # lengths of average and variance vectors
  if(length(Av)!=Nv) {stop("Unequal lengths of average and variance vectors")} 
  if(Nv<3) {stop("At least 3 samples are required")}
  x<-as.vector(Av)                                                                     # average counts vector
  Vari<-as.vector(Va)                                                                  # variance vector  
  Nc<-length(x)                                                                        # number of remaining samples
  VarT0=1/sum(1/Vari)
  w0=(1/Vari)/sum(1/Vari)
  x0=sum(x*w0)
  VarE0<-sum(w0^2*(x-x0)^2)/(1-sum(w0^2))
  if(VarE0<=VarT0) {Vp=0}
  else{
    f <- function(Vp,x=x,Vari=Vari) {
      wprop<-1/(Vari+Vp)                                                               # proportional weights
      VarT<-1/sum(wprop)                                                               # expected variance
      w <- wprop/sum(wprop)                                                            # normalized weights
      x1 = sum(x*w)                                                                    # weighted average
      VarE<-sum(w^2*(x-x1)^2)/(1-sum(w^2))                                             # measured variance
      VarE-VarT                                                                
    }
    Vp1 = max(Vari)                                                                    # finding Vp, at which expected variance is equal to measured
    ur = uniroot(f, c(0,Vp1),x=x,Vari=Vari,check.conv=T,extendInt="downX", tol = min(Vari)*1e-4)
    Vp = ur$root
  }
  if(Vp<0){Vp=0}                                                                       # changing negative Vp to Vp=0 (known effect of insufficient sampling)
  w=(1/(Vari+Vp))/sum(1/(Vari+Vp))                                                     # calculating normalized statistical weight
  return(w)
}
#
# Weighted t-test for multiple samples
# Uses the sample matrix generated by SampleMatrix()
WT.MultiSample <- function(sample.matrix,features=NULL,t.test=FALSE ,min.pct=0.03,fc.thr=1,max.pval=1,df.correction=FALSE,sum.w2=0.4,min.cells=10,min.count=10) {
  AV1<-sample.matrix[[1]]                                                            # read average expression matrix
  var1<-sample.matrix[[2]]                                                           # read variance matrix
  AV2<-sample.matrix[[3]]
  var2<-sample.matrix[[4]]
  pct1<-sample.matrix[[5]]                                                           # read expression fraction matrix
  pct2<-sample.matrix[[6]]
  cnt1<-sample.matrix[[7]]
  cnt2<-sample.matrix[[8]]
  Ncd1<-sample.matrix[[9]]
  Ncd2<-sample.matrix[[10]]
  Agc1<-sample.matrix[[11]]
  Agc2<-sample.matrix[[12]]
  Sstats<-sample.matrix[["Sstats"]]
  fr <- .resolve_features(features, rownames(AV1))
  GeneList <- fr$genes                                                                # check for genes to be analyzed
  OrphanGenes <- fr$orphan
  .validate_common_params(fc.thr = fc.thr, min.pct = min.pct, max.pval = max.pval,
                          min.count = min.count, sum.w2 = sum.w2, min.cells = min.cells)
  data1<-as.matrix(AV1)                                                              # setting up data matrices
  data2<-as.matrix(AV2)                                                              
  N1=ncol(data1)                                                                     # number of samples in group 1 included in the analysis
  N2=ncol(data2)                                                                     # number of samples in group 2 included in the analysis
  wi.1eq=rep(1/N1, N1)                                                               # equal weights for samples in group 1
  wi.2eq=rep(1/N2, N2)                                                               # equal weights for samples in group 2
  nmax <- length(GeneList)
  output <- data.frame(log2FC=rep(NA_real_, nmax), p.value=rep(NA_real_, nmax),
                       `Wtd.%UMI.1`=rep(NA_real_, nmax), `Sd.%UMI.1`=rep(NA_real_, nmax), `Av.cell.fr.1`=rep(NA_real_, nmax),
                       `N.+_cells.1`=rep("", nmax), `Counts.1`=rep("", nmax), `Counts/cell.1`=rep(NA_real_, nmax), `Sum_w^2.1`=rep(NA_real_, nmax),
                       `Wtd.%UMI.2`=rep(NA_real_, nmax), `Sd.%UMI.2`=rep(NA_real_, nmax), `Av.cell.fr.2`=rep(NA_real_, nmax),
                       `N.+_cells.2`=rep("", nmax), `Counts.2`=rep("", nmax), `Counts/cell.2`=rep(NA_real_, nmax), `Sum_w^2.2`=rep(NA_real_, nmax),
                       check.names = FALSE, stringsAsFactors = FALSE)
  rowi<-0                                                                            # output row counter
  print("Performing weighted t-test:")
  pb <- txtProgressBar(min = 0, max = length(GeneList), initial = 0, style = 3)      # initialize progress bar
  for (rownum in seq_along(GeneList)) {                                              # gene by gene DGE calculation loop
    gene <- GeneList[[rownum]]
    Xi1<-data1[gene,]                                                                 # data vectors for groups 1 and 2  
    Xi2<-data2[gene,]
    VARi1<-var1[gene,]                                                                # variance vectors for groups 1 and 2
    VARi2<-var2[gene,]
    PCTi1<-pct1[gene,]                                                                # expression fraction vectors for groups 1 and 2 
    PCTi2<-pct2[gene,]
    CNTi1<-cnt1[gene,]                                                                # count/cell vectors for groups 1 and 2 
    CNTi2<-cnt2[gene,]
    NCDi1<-Ncd1[gene,]                                                                # number of positive cells vectors
    NCDi2<-Ncd2[gene,]
    AGCi1<-Agc1[gene,]                                                                # aggregate count vectors
    AGCi2<-Agc2[gene,]
    Ns1=sum(NCDi1>=min.cells)                                                        # number of samples containing >min.cells
    Ns2=sum(NCDi2>=min.cells)
    CellStat1=paste(NCDi1,collapse = ":")                                            # number of positive cell vector output
    CellStat2=paste(NCDi2,collapse = ":")
    CountStat1=paste(AGCi1,collapse = ":")                                           # aggregate count vector output
    CountStat2=paste(AGCi2,collapse = ":")
# selecting genes meeting minimum sample and expression requirements    
    if (N1 >= 3 && N2 >= 3 && (mean(PCTi1)>=min.pct || mean(PCTi2)>=min.pct) && (Ns1>=3 || Ns2>=3) && (sum(AGCi1)>=min.count || sum(AGCi2)>=min.count)){
# selection criteria: (a) Number of samples in each group >= 3 (N1 >= 3 && N2 >= 3)
#                     (b) Fraction of cells expressing the gene in 1 of 2 groups >= min.pct (mean(PCTi1)>=min.pct || mean(PCTi2)>=min.pct)
#                     (c) Number of samples with enough cells (>=min.cells) expressing the gene >= 3 in one of 2 groups (Ns1>=3 || Ns2>=3)
#                     (d) Aggregate count in one of two sample groups >= min.count (sum(AGCi1)>=min.count || sum(AGCi2)>=min.count)
      wi.1<-if(t.test==TRUE || Ns1<3) {wi.1eq} else {IterVar(Xi1,VARi1)}             # calculating weights for groups 1 and 2
      wi.2<-if(t.test==TRUE || Ns2<3) {wi.2eq} else {IterVar(Xi2,VARi2)} 
      wi.1sq<-sum(wi.1^2)                                                            # sum of w^2
      wi.2sq<-sum(wi.2^2)
      wi.1<-if(wi.1sq>sum.w2) {wi.1eq} else(wi.1)                                    # switching to equal weights when sum(w^2)>sum.w2 or Ns<3 
      wi.2<-if(wi.2sq>sum.w2) {wi.2eq} else(wi.2)                                    #(conservative average and variance calculation)
      Xi1av<-sum(Xi1*wi.1)                                                           # weighted average expression for groups 1 and 2
      Xi2av<-sum(Xi2*wi.2)
      Xi1sd<-sqrt(sum(wi.1^2*(Xi1-Xi1av)^2)/(1-sum(wi.1^2)))                         # standard deviations for the weighted averages
      Xi2sd<-sqrt(sum(wi.2^2*(Xi2-Xi2av)^2)/(1-sum(wi.2^2)))
      fc <- Xi1av/Xi2av                                                              # fold change (FC)
      if (!is.na(fc)){                                                                # removing 0/0 division
        if (fc >= fc.thr || fc <= 1/fc.thr) {                                        # checking FC threshold
          if(df.correction) {wTtest <- as.numeric(alt.wttest2(Xi1,Xi2,wi.1,wi.2))}   # weighted t-test with effective df
          else {wTtest <- as.numeric(alt.wttest(Xi1,Xi2,wi.1,wi.2))}                 # weighted t-test without df correction
          if(is.na(wTtest) || wTtest <= max.pval) {                                   # keep exact prior behavior: include NA p-values or <= max.pval
            rowi<-rowi+1
            output[rowi, ] <- list(log(fc,2), wTtest, Xi1av, Xi1sd, mean(PCTi1), CellStat1, CountStat1, mean(CNTi1), mean(wi.1sq),
                                    Xi2av, Xi2sd, mean(PCTi2), CellStat2, CountStat2, mean(CNTi2), mean(wi.2sq))
            row.names(output)[rowi]<-gene
          }
        } 
      }
    }
    setTxtProgressBar(pb, rownum)                                                     # progress bar update
  }
  close(pb)                                                                           # close progress bar
  output <- .trim_output(output, rowi)
  .warn_orphans(OrphanGenes)
  param<-as.character(c(t.test,min.pct,fc.thr,max.pval,min.cells,min.count,sum.w2,df.correction))
  names(param)<-c("t.test","min.pct","fc.thr","max.pval","min.cells","min.count","sum.w2","df.correction")
  list(DGE=output,Sstats=Sstats,parameters=param)
}
#
#Simplified wrapper function for one-step analysis
DGE.MultiSample<-function(object,samples.1=NULL,samples.2=NULL,features=NULL,t.test=FALSE, min.pct=0.03,fc.thr=1,max.pval=1,
                          icc="i",df.correction=FALSE,sum.w2=0.4,min.cells=10,min.count=10) {
  if(is.null(samples.1) || is.null(samples.2)) {stop("Define sample name vectors using samples.1= and samples.2=")}
  N.1=length(samples.1)                                                              # number of samples in each group
  N.2=length(samples.2)
  if(N.1<3 || N.2<3) {stop("At least 3 samples per group are required")}             # early check for sample numbers
  .validate_common_params(fc.thr = fc.thr, min.pct = min.pct, max.pval = max.pval,
                          min.count = min.count, sum.w2 = sum.w2, min.cells = min.cells)
  object.m<-CntAv(object,features,icc=icc)                                                   # Count averaging within each sample
  SM<-SampleMatrix(object.m,samples.1,samples.2)                                     # Assembly of sample matrices
  output<-WT.MultiSample(SM,features,t.test,min.pct,fc.thr,max.pval,df.correction,sum.w2,min.cells,min.count) # Analysis of sample matrices
  param<-as.character(c(t.test,min.pct,fc.thr,max.pval,icc,df.correction))
  names(param)<-c("t.test","min.pct","fc.thr","max.pval","icc","df.correction")
  list(DGE=output$DGE,Sstats=output$Sstats,parameters=output$parameters)
}
###########################################
