######################################
#    LIBRARIES
######################################
if (!requireNamespace("BiocManager", quietly = TRUE))
  install.packages("BiocManager")
library(dplyr)
library(Seurat)
library(cowplot)
library(ggplot2)
library(readr)
library(tidyverse)
library(hdf5r)
library(patchwork)
#
# DATA REQUIREMENTS:
#
# working directory must contain:
# folder tree: outs/binned_outputs/square_008um/spatial folder tree
# files:
# *.csv files with selected area barcodes exported from Loupe Browser
# outs/binned_outputs/square_008um/filtered_feature_bc_matrix.h5
# outs/binned_outputs/square_008um/spatial/scalefactors_json.json
# outs/binned_outputs/square_008um/spatial/tissue_positions.parquet
# outs/binned_outputs/square_008um/spatial/tissue_hires_image.png
# outs/binned_outputs/square_008um/spatial/tissue_lowres_image.png
#
# The latter 2 files may need to be copied from the outs/spatial folder
# in the original VisiumHD results
#
# FUNCTIONS:
#
# LoadHD8um(results.dir) - creates Seurat object from the *.h5 file using the high resolution image
# results.dir is the working directory, e.g., "D:/VisiumHD/experiment1"
#
# CropHD(object,barcodes,padding=0.05, xoffset=8, yoffset=8) - crops the Seurat object (including the embedded image) to the selected area
# Ignore the warnings generated by this function
# barcodes is the name of the *.csv file without the .csv extension that contains the selected area barcodes, e.g., "D:/VisiumHD/experiment1/Top"
# Use the xoffset and yoffset parameters for fine-tuning the alignment of the VisiumHD bins with the hight resolution image
#
# GeneMap(object,map.features="nCount_Spatial.008um",map.limits=c(0,10000),pt.size=1,map.breaks=c(0,2500,5000,7500,10000)
# Overlays tissue image with color coded intensity of the feature defined by the map.features parameter, 10000 intensity corresponds to 100% UMI
# While multiple features can be defined, this function has been designed for visualizing a single feature.
#
######################################
#    Load HiRes VisiumHD Object Function
######################################
LoadHD8um <- function(results.dir){
  outs.dir <- str_c(results.dir,"/outs")
  HDimage.dir <- str_c(outs.dir,"/binned_outputs/square_008um/spatial")
  object <- Load10X_Spatial(data.dir = outs.dir, bin.size = c(8))
  hires <- Read10X_Image(HDimage.dir, image.name = "tissue_hires_image.png")
  #Replacing LowREs image with HiRes one
  lowres <- object@images$slice1.008um
  hires@scale.factors$lowres = hires@scale.factors$hires
  hires@assay = lowres@assay
  hires@key = lowres@key
  object@images$slice1.008um = hires
  object@meta.data[["nCount_Col1"]] <- FetchData(object,vars="Col1a1",layer="counts")[["Col1a1"]]+FetchData(object,vars="Col1a2",layer="counts")[["Col1a2"]]
  object@meta.data[["nCount_nonCol"]] <- object@meta.data[["nCount_Spatial.008um"]]-object@meta.data[["nCount_Col1"]]
  object@meta.data[["ColRC"]] <- object@meta.data[["nCount_Col1"]]*10000/object@meta.data[["nCount_Spatial.008um"]]
  return(object)
}
#
######################################
#    Crop VisiumHD Object Function
#     Use xoffset and yoffset
#   for more precise image alignment
######################################
CropHD <- function(object,barcodes,padding=0.05,xoffset=8,yoffset=8){
  file.name<-str_c(barcodes,".csv")
  SbSt <- read.csv(file.name)
  SbSt_barcodes <- SbSt$Barcode
  object_SbSt <- subset(object, cells=SbSt_barcodes)
  #calculating coordinates for image cropping
  sf <- object@images$slice1.008um@scale.factors$hires
  xmin <- sf*object_SbSt@images$slice1.008um@boundaries$centroids@bbox[[1,1]]
  xmax <- sf*object_SbSt@images$slice1.008um@boundaries$centroids@bbox[[1,2]]
  ymin <- sf*object_SbSt@images$slice1.008um@boundaries$centroids@bbox[[2,1]]
  ymax <- sf*object_SbSt@images$slice1.008um@boundaries$centroids@bbox[[2,2]]
  xminp <- xmin-padding*(xmax-xmin)
  xmaxp <- xmax+padding*(xmax-xmin)
  yminp <- ymin-padding*(ymax-ymin)
  ymaxp <- ymax+padding*(ymax-ymin)
  sf <- object@images$slice1.008um@scale.factors$lowres
  object_Crop <- object_SbSt
  object_Crop@images$slice1.008um@image <- object@images$slice1.008um@image[c(xminp:xmaxp), c(yminp:ymaxp), ]
  object_Crop@images$slice1.008um@boundaries$centroids <- Crop(object_SbSt@images$slice1.008um@boundaries$centroids, y = c(xmin/sf, xmax/sf), x = c(ymin/sf,ymax/sf), coords = "plot")
  # Correct for centroid coordinate offset
  temp <- object_Crop@images$slice1.008um@boundaries$centroids@coords
  for (rownum in c(1:nrow(temp))) {
    for (colnum in c(1:ncol(temp))) {
      if (colnum == 1) {
        temp[rownum, colnum] <- temp[rownum, colnum] - (xminp/sf) + yoffset
      } else if (colnum == 2) {
        temp[rownum, colnum] <- temp[rownum, colnum] - (yminp/sf) + xoffset 
      }
    }
  }
  object_Crop@images$slice1.008um@boundaries$centroids@coords <- temp
  object_Crop@images$slice1.008um@boundaries$centroids@bbox[[1,1]] <- 0
  object_Crop@images$slice1.008um@boundaries$centroids@bbox[[1,2]] <- xmax/sf
  object_Crop@images$slice1.008um@boundaries$centroids@bbox[[2,1]] <- 0
  object_Crop@images$slice1.008um@boundaries$centroids@bbox[[2,2]] <- ymax/sf
  names(object_Crop@images) <- barcodes
  Key(object_Crop[[barcodes]]) <- str_c(barcodes,"_")
  return(object_Crop)
}
#
######################################
#    GeneExpressionMap
######################################
#
GeneMap <- function(object,map.features="nCount_Spatial.008um",map.limits=c(0,10000),pt.size=1,map.breaks=c(0,2500,5000,7500,10000),
                    map.colors= c("#00008b","#00ff8b","yellow","#cf2222"),image.crop=FALSE,colorbar.position="bottom",legend.size=1){
  SpatialFeaturePlot(object, features = map.features, pt.size.factor = pt.size,crop = image.crop)+
    ggplot2::scale_fill_gradientn(limits=map.limits,breaks=map.breaks,colors=map.colors)+
    theme(legend.position = colorbar.position, legend.key.width = unit(1*legend.size,"cm"),
          legend.key.height = unit(0.6*legend.size,"cm"),
          legend.title = element_text(size=14*legend.size),
          legend.text = element_text(size=12*legend.size))
}
#